### ISSUE TITLE
Turnip Price Guaranteed Maximum shows Infinity and Guaranteed Minimum shows Infinity

### ISSUE THREAD

**Issue by anch56** [mikebryant/ac-nh-turnip-prices#250] opened 2020-04-23 20:24 UTC
The Turnip Prophet was working fine until I entered Wednesday's afternoon price. This led the Output to show 999 to 0 for all days.

Here is my permalink: https://turnipprophet.io/?prices=102.92.87.116.179.316.107.134.....&pattern=3

**Comment by theRTC204** [comment] 2020-04-23 21:04
The game's math suggests that these numbers are impossible. Let's break it down.

The only pattern in the game that has larger than a 2x multiplier is the Large Spike - so, based on a sell price of 102, that would put the peak return for any other pattern at 204. From this we can deduce that you had a Large Spike pattern for the week because you had a sell price that exceeded that amount.

So, looking at the Large Spike pattern, it begins with anywhere from 0 to 7 decreasing periods. Those decreasing periods start at the highest multiplier of 0.9 and work there way down from there. So based on your buy price that would peak at 92 - this means any value above 92 indicates the start of the spike; in other words, by Tuesday AM you were starting your spike.

The spike is exactly 5 periods long, and is defined like this:
```cpp
    sellPrices[work++] = intceil(randfloat(0.9, 1.4) * basePrice);
    sellPrices[work++] = intceil(randfloat(1.4, 2.0) * basePrice);
    sellPrices[work++] = intceil(randfloat(2.0, 6.0) * basePrice);
    sellPrices[work++] = intceil(randfloat(1.4, 2.0) * basePrice);
    sellPrices[work++] = intceil(randfloat(0.9, 1.4) * basePrice);
```

Based on that, the Tuesday AM range was 0.9-1.4, and you received a 116 sell price which is in range `116 / 102 = 1.137254901960784`.

Next, your Tuesday PM range was 1.4-2.0, and you received a price of 179 which is in range as well `179 / 102 = 1.754901960784314`.

Then we get into Wednesday AM, which has a possible range of 2.0-6.0, and your price of 316 is again within range `316 / 102 = 3.098039215686275`.

And this is where we get to the problem. The next period, Wednesday PM, has a possible range of 1.4-2.0 again, and your price of 107 is well out of range `107 / 102 = 1.049019607843137‬`... that's a whole `0.35` out of range, in fact.

Then we get to your last tracked period, Thursday AM, which has a possible range of 0.9-1.4 and here your number comes back into range `134 / 102 = 1.313725490196078`.

This suggests that the number for Wednesday AM was entered incorrectly.

**Comment by anch56** [comment] 2020-04-23 21:35
I had a Small Spike last week but this week it seems to have been a Large Spike. Should I have changed my previous week's pattern choice after my Wednesday AM price was higher than usual?

**Comment by theRTC204** [comment] 2020-04-23 21:46
No, that wouldn't be necessary. The previous week pattern field is only there to assist with the probability calculations - it doesn't have any effect on the numbers you'd end up with.

**Comment by andyaffleck** [comment] 2020-04-24 13:33
I'm having the same issue every since... Tuesday? I have double checked my numbers. https://turnipprophet.io?prices=.121.143.153.84.78.72.101.141.67...&first=true

**Comment by theRTC204** [comment] 2020-04-24 13:45
> I'm having the same issue every since... Tuesday? I have double checked my numbers. https://turnipprophet.io?prices=.121.143.153.84.78.72.101.141.67...&first=true

@andyaffleck your permalink shows you have First Time Buyer enabled, but your numbers suggest that's not possible. If it truly were the first time Turnips were bought on your island, you would have been locked into a Small Spike pattern, but your numbers clearly show a Fluctuating pattern. If you disable the First Time Buyer then two possible predictions appear for the rest of the week.

Are you absolutely 100% certain that this week was the first week any resident of your island bought Turnips?

**Comment by andyaffleck** [comment] 2020-04-24 14:57
Ahhh! I bought my turnips on another island... they were cheaper than mine.

**Comment by theRTC204** [comment] 2020-04-24 16:59
That explains it then. You need to make sure all of the data you've entered into the tool is from the same island. The Turnip prices are fixed to an island, not to a player.

(marking these comments as off-topic)

**Comment by kbarnes3** [comment] 2020-04-28 20:55
I'm also in an "infinity" state after entering my numbers.

https://turnipprophet.io?prices=94.63.57.124.144........&pattern=3

I tracked my prices last week through Thursday and had a 100% chance of being a small spike. My purchase price was definitely 94 (as confirmed via chat logs with friends). I also feel confident about reporting my other numbers. Everything was looking right on track for a fluctuating pattern until Tuesday PM when I got a price of 144. I've triple checked that's the price I'm getting right now.

All these values come from my own island and I'm running version 1.2.0 of the game.

**Comment by carlylemiii** [comment] 2020-04-28 22:46
I'm also seeing this :(

https://turnipprophet.io?prices=103.78.89.84.142........ (I don't know my pattern from the previous week)

**Comment by kkslider-dev** [comment] 2020-04-29 10:27
We have a group where we follow prices in different island. This week we have a new member and he seems to have a big spike being his first time buying turnips. Even deactivating the "first time", as I though that first time always have small spikes, it doesn't match any pattern. I've asked him and he is sure he has not bought turnips before.

This is the link to his records:
https://turnipprophet.io/?prices=90.91.86.83.133.158.358......&first=true

**Comment by peter50216** [comment] 2020-04-29 10:35
> We have a group where we follow prices in different island. This week we have a new member and he seems to have a big spike being his first time buying turnips. Even deactivating the "first time", as I though that first time always have small spikes, it doesn't match any pattern. I've asked him and he is sure he has not bought turnips before.
> 
> This is the link to his records:
> https://turnipprophet.io/?prices=90.91.86.83.133.158.358......&first=true

Some questions:
* Is the turnip price 90 the price on their own island?
* Did they buy the turnip on their own island?

The most possible case I can think of is that they buy turnips on others island for 90 bells, since removing the price & first buyer checkbox and there's a prediction.

**Comment by kkslider-dev** [comment] 2020-04-29 10:38
Yeah, I'm thinking the same, he told me that was the price that he buy for sure and we don't have in our group any other island with such a price on sunday, but maybe he was to a different one to buy, I don't want keep asking him to avoid conflicts haha. 

If that the case, that affect to the first time value? It has to be the first time you have buy in your island?

**Comment by peter50216** [comment] 2020-04-29 10:58
Yes, the first time buyer value only need to be checked on the week that you (or some resident) buy turnips on their own island for the first time. Buying from others island doesn't affect that flag.

**Comment by Eond** [comment] 2020-04-29 15:13
I've encountered this as well.
https://turnipprophet.io/?prices=106.49.77.67.130.94.129......
When I check with another predictor, it can make a graph, but not Turnip Prophet. It just shows infinity.
I would have tossed it aside as a human error if the other site didn't provide a graph. Could this sequence of prices be a fluctuating pattern?

**Comment by kbarnes3** [comment] 2020-04-29 17:33
It looks like this comment from @peter50216 explains what I was seeing:

> Yes, the first time buyer value only need to be checked on the week that you (or some resident) buy turnips on their own island for the first time. Buying from others island doesn't affect that flag.

It's possible this was the first week I actually bought turnips from my own island. Checking that box makes the predictions sane and accurate (so far) again.

**Comment by mikebryant** [comment] 2020-04-29 18:01
I'm afraid that this thread has become unwieldy, and as it no longer relates to the original author's prices, I'm going to close it. Please feel free to create separate issues, if you think there's an issue with your numbers specifically.

@Eond Most of the numbers look like a fluctuating pattern, but the first number is impossible - taking that out gives you a valid prediction.
In the fluctuating pattern numbers that start each phase are either between 0.6 and 0.8 of the input, or between 0.9 and 1.4 of the input. Therefore the first number is at a minimum `0.6*106 == 63.6`, 49 is not possible.

**Closed by mikebryant** 2020-04-29 18:01 UTC
Labels: prediction
