### ISSUE TITLE
First time buyer definition

### ISSUE THREAD

**Issue by DonQuixoote** [mikebryant/ac-nh-turnip-prices#73] opened 2020-04-13 01:10 UTC
Hi, I have to say it is an amazing tool for turnip market. However I'm a little bit confused by how this tool defines a 'first time buyer'. My case is: Daisy Mae came to my island for the first time this week but I actually bought turnips from another island. So in this case should I mark myself as a first time buyer?

**Comment by theRTC204** [comment] 2020-04-13 01:19
As the text in the tool says, it only matter if you are buying on _your island_. If you have never bought on your island, then it is not your first week buying on your island.

**Comment by DonQuixoote** [comment] 2020-04-13 01:26
> 
> 
> As the text in the tool says, it only matter if you are buying on _your island_. If you have never bought on your island, then it is not your first week buying on your island.

Thank you for replying. So do you mean if I should buy turnips on my island for the first time at next week, I shall check yes as a first time buyer and the buying price itself doesnt matter?

**Comment by theRTC204** [comment] 2020-04-13 01:35
Yes, the first time you buy turnips on your own island you should indicate as such in the tool.

Please refer to the other issues opened about first buy for a more detailed explanation as to why that matters. https://github.com/mikebryant/ac-nh-turnip-prices/issues/44#issuecomment-611287258

**Comment by DonQuixoote** [comment] 2020-04-13 01:40
> 
> 
> Yes, the first time you buy turnips on your own island you should indicate as such in the tool.
> 
> Please refer to the other issues opened about first buy for a more detailed explanation as to why that matters. [#44 (comment)](https://github.com/mikebryant/ac-nh-turnip-prices/issues/44#issuecomment-611287258)

Okay thank you for your explanation!

**Comment by psycho91-1** [comment] 2020-04-13 11:11
One question: if I NEVER bought turnips on my island but always elsewhere, I should answer no? So the my price on sunday still matters even if I never bought turnips on my island?

**Comment by psycho91-1** [comment] 2020-04-13 11:20
I'll try explain myself better, also by another question: so if I never bought on my island, what price will matter on my prices? The sunday price should be the price I bought the turnips from? Or the price of Daisy Mae on MY island, which wasn't regenerated since I didn't buy from her?

**Comment by peter50216** [comment] 2020-04-13 11:26
> One question: if I NEVER bought turnips on my island but always elsewhere, I should answer no? So the my price on sunday still matters even if I never bought turnips on my island?
Yes that's correct.

> I'll try explain myself better, also by another question: so if I never bought on my island, what price will matter on my prices? The sunday price should be the price I bought the turnips from? Or the price of Daisy Mae on MY island, which wasn't regenerated since I didn't buy from her?

Should be the price on your island, not the price where you bought the turnips from.

**Comment by MichelHerve** [comment] 2020-04-13 12:08
Hi, I'm playing with my siblings on the same island and I have never bought turnips but other people on my island did. Do I have to say that this is the first time buying in that case, or is this option for all players?

**Comment by peter50216** [comment] 2020-04-13 12:42
> Hi, I'm playing with my siblings on the same island and I have never bought turnips but other people on my island did. Do I have to say that this is the first time buying in that case, or is this option for all players?

I have no experience in multiple player on the same console, but I'd guess that all player would get the same price? So it should only matter when the first player ever buying turnips on that island.

These are purely speculation though since the original reversed code / Ninji's tweet doesn't clearly specified how things is really coded here.

**Comment by theRTC204** [comment] 2020-04-13 12:58
The game only has a single island, regardless of which profile is playing on the console, and the flag for first time buyer in the game code is a global one.

So, my assumption would be that during the first week that anyone bought on your island, that week should be marked as `Yes`.

All other weeks, before and after that week, should be marked as `No`.

**Comment by ColMelvin** [comment] 2020-04-14 04:25
Since the game has a distinction between the primary player and secondary players, it may be that the primary player needs to buy; experimentation required.

In my experience, when the primary player bought their first turnips one week and a secondary player bought there first turnips a week later, setting `First Time Buyer` to `No` provided more accurate predictions.

**Comment by theRTC204** [comment] 2020-04-14 06:10
The game may have a distinction between players, but my understanding is the island does not. I haven't played the game with a secondary profile on a fresh save to validate that myself though.

**Comment by theRTC204** [comment] 2020-04-19 05:38
Closing this as a duplicate of #44.

**Closed** 2020-04-19 05:38 UTC
Labels: duplicate
