### ISSUE TITLE
Transfer Previous Week's Pattern?

### ISSUE THREAD

**Issue by renmir** [mikebryant/ac-nh-turnip-prices#365] opened 2020-05-13 20:06 UTC
Not really an issue, just wondering if there's plans to include a button next to Reset Turnip Prophet button (or a checkbox) that would automatically set the pattern that you had the following week by pulling it from the data you've given? Maybe make it where you have to have at least 6 fields or something to make sure you've got an accurate pattern listed.

**Comment by theRTC204** [comment] 2020-05-13 22:08
Someone in the community submit #323 that essentially does exactly what you're describing.

**Comment by mikebryant** [comment] 2020-05-15 18:03
Thanks for the idea - I'm closing this as a duplicate of #324

**Closed by mikebryant** 2020-05-15 18:03 UTC
Labels: duplicate
