### ISSUE TITLE
Friend showed me Turnip Prophet, broke it on my first week.

### ISSUE THREAD

**Issue by LordGeovanni** [mikebryant/ac-nh-turnip-prices#96] opened 2020-04-14 20:38 UTC
I dont know too much on Computer Programing, but I figured I could collect my data this week. I had a weird week so far and my prices broke the calculator so I figured I should at least report the amounts.

I do not know what my turnip trend was last week. Buy price was 95.
Monday was 52 turnips, then 48.
Tuesday was 95 turnips, then 137.

Expectation was that Tuesday evening was going to be a max of 133. As I go through this week, I will continue to gather the numbers to help out further.

**Comment by Trevor-Welch** [comment] 2020-04-14 21:46
We are currently taking a second-look at the algorithm.

Please post your final numbers at the end of the week if you can, so we can use them to help fix it!

**Comment by LordGeovanni** [comment] 2020-04-14 21:54
Will be glad to.

**Comment by Varijon** [comment] 2020-04-14 23:15
Same issue here, sunday: 93, previous week fluctuating
Monday 80, 76
Tuesday 70, 67
Odd thing is, it breaks the instant I put Tuesday AM in, while the calculator was working fine 12 hours ago.

**Comment by theRTC204** [comment] 2020-04-14 23:48
@Varijon yes, that makes sense. Prior to that commit, we were incorrectly expanding the range of possible values by one.

It's a bit hard to explain, but the commit you linked is _not_ the cause of the issue. The fact that the value 70 ever worked for Tuesday AM is actually a symptom of another issue entirely (that issue was fixed in the commit you linked).

We still need to address the underlying problem where the predictions are incorrectly ruling out values that should be acceptable.

**Closed** 2020-04-15 13:14 UTC
Labels: Prediction

**Comment by LordGeovanni** [comment] 2020-04-19 06:42
I lost some data from a computer crash. But my data is
Buy at 95, Mon 52/48, Tues 95/137, Wed. 142/144, Thurs, 142/73, Fri. ?/?, Sat. ?/57.

I lost Friday and Sat. Morn. But I can confirm the numbers were within the range shown after the edit to the prophet that happened 4 days ago
