### ISSUE TITLE
Data not saved between sessions.

### ISSUE THREAD

**Issue by Skylortrexler** [mikebryant/ac-nh-turnip-prices#381] opened 2020-05-19 18:40 UTC
**Things to check**
- Have you forced a refresh in your browser (e.g. ctrl+F5 in Chrome/Firefox)?
  - yes
- Have you made sure the first time buyer option is correct? If you're unsure, try it both ways
  - yes
- Have you time-travelled this week? Travelling backwards resets the prices, and therefore you must not put prices in from both before & after the time-travel
  - no

**Describe the bug**
The entered user data is not being saved. 

**To Reproduce**
1. Enter data in any field
2. Close browser
3. Reopen website
4. Data is gone

**Permalink to your prices**
https://turnipprophet.io?prices=107...105.........&pattern=3 not like it matters because it will be deleted when I reopen the browser

**Expected behavior**
I expected that my data will be saved like it has been for the last few weeks. Hardly helps have a tracker if I have to manually track it as well.

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Browser: Chrome 
 - Version:  81.0.4044.138 (Official Build) (64-bit)

**Additional context**
Has been deleting my data every time since 5/17

**Comment by C00kiekiller** [comment] 2020-05-19 19:08
My wife and I have exactly the same problem.

**Comment by 3nyder** [comment] 2020-05-20 00:01
Same problem here, Chrome on Android, on two different devices, phone and tablet same issue 

It was saving before (from Sunday until Tuesday morning) but we lost all info today

First time we encountered this issue, past weeks everything was ok

**Comment by Mr-dotcom145** [comment] 2020-05-20 12:43
I agree, this started happening 5/17 on my account as well.  Used to work wonderfully.

**Comment by GldRush98** [comment] 2020-05-20 13:53
Same problem, started Sunday as well. Used it for weeks and it always remembered. I have lost the data I've entered every single day this week. I have had to start writing my numbers down and putting them back in to the app every morning.

**Comment by acidaris** [comment] 2020-05-20 16:50
I suspect this is an issue from #325, as when looking at the data stored in localstorage on my desktop computer when my data reset, I had a `darkmode = true`  value which is a sign of https://github.com/sandoche/Darkmode.js (the old dark mode) instead of the `theme` value which is the new one.

Possibly if a user has the "old" format of data during initialization of the webpage, something breaks, and data gets cleared?  I'm attempting to reproduce.

**Comment by Tekaoh** [comment] 2020-05-20 23:51
Duplicate of #375

**Comment by NtheOtaku** [comment] 2020-05-21 14:11
It's been a problem for me too. What I find strange though is that my browser has cookies saved for the site.
I'm going to assume it's because I keep my ACNH-related tabs in a saved collection, which I open in a new window whenever I log on to track my prices. But what I find odd is that the other sites I use for this (_ac-turnip.com_ and _elxris.github.io/Turnip-Calculator_) are still able to store my price data, even between browsing sessions.

**Comment by Tekaoh** [comment] 2020-05-21 15:23
> I'm going to assume it's because I keep my ACNH-related tabs in a saved collection, which I open in a new window whenever I log on to track my prices.

Nah, it's definitely not because of anything you're doing. There's a problem in the app somewhere. Hopefully we'll have it solved very soon.

**Comment by xSke** [comment] 2020-05-21 17:41
Can reproduce, unfortunately. Any way to recover data or is it just gone?

**Comment by mikebryant** [comment] 2020-05-24 12:31
Closing as a duplicate of #375

**Closed by mikebryant** 2020-05-24 12:31 UTC
Labels: bug, duplicate
