### ISSUE TITLE
Inaccurate Pattern Recognition Leads to Inaccurate % chance

### ISSUE THREAD

**Issue by astranberg** [mikebryant/ac-nh-turnip-prices#205] opened 2020-04-20 21:46 UTC
Hey guys,

Got this starting pattern this week and noticed an issue with the fluctuating pattern. Type in 99 as the buy price and you'll see Fluctuating properly predicting the range of prices is 90 to 139 or 60 to 80.
https://turnipprophet.io?prices=99&pattern=3

Type 89 into Monday AM, and fluctuating 90 to 139 has decided it will adopt 89 as a possibility, when it is in fact impossible.
https://turnipprophet.io?prices=99.89...........&pattern=3

It works for other numbers in the 81-89 range as well.

Thoughts?

**Comment by scizzorz** [comment] 2020-04-20 22:02
See https://github.com/mikebryant/ac-nh-turnip-prices/issues/198 for more info

**Comment by theRTC204** [comment] 2020-04-20 23:47
Going to close this as a duplicate of #198

**Closed** 2020-04-20 23:47 UTC
Labels: duplicate
