### ISSUE TITLE
Pattern matching error when I enter Monday AM value

### ISSUE THREAD

**Issue by XcellMiguel** [mikebryant/ac-nh-turnip-prices#198] opened 2020-04-20 08:02 UTC
Hi,

I bought turnips at 90 on Sunday, last week was using the fluctuating pattern.

Thus the app predicts 35% for Small Spike if Monday is between 36 and 82 : https://turnipprophet.io?prices=90&pattern=0
It also predicts 30% for Large Spike if Monday is between 77 and 82.

But when I enter the real Monday AM value : 73, it predicts Large Spike, which seems false as it's not in the valid range https://turnipprophet.io?prices=90.73...........&pattern=0

If I enter a value for Monday PM that is expected to be in the Small Spike range, it shows the right expectations, but still displays the Large Spike graph, but it should not as Large Spike can't happen.

The other turnip app (Turnip Calculator) seems to handle that the right way for this week.
Or maybe Large Spike is possible and the other app is wrong ?

**Comment by peter50216** [comment] 2020-04-20 08:05
This is because of the FUDGE_FACTOR added in code, trying to make that even there's small error in floating point operations / user input, there would still be some prediction given.

**Comment by theRTC204** [comment] 2020-04-20 12:30
Yup, this is one of the unfortunate side effects of the fudge factor we added... Without it, we were seeing a lot of reports of no pattern matches found; with it there will be cases along the edges of ranges where incorrect pattern matches are made.

Not really sure how to improve this...

**Comment by XcellMiguel** [comment] 2020-04-20 12:35
Now with the added real value of Monday PM (69) it says 100% for Small Spike. Which seems logical.
https://turnipprophet.io?prices=90.73.69..........&pattern=0

But it now shows very tiny percentages (under 0.01%) for Large Spike and Variable, which are unlikely to happen.

Maybe adding a setting to disable the fudge factor would help if possible?

**Comment by theRTC204** [comment] 2020-04-20 13:05
Adding a toggle could help for people who understand what it means, which I would argue is probably an extremely small percentage of people who use the app daily.

We have to prioritize ease-of-use over complex customization.

**Comment by spfennell** [comment] 2020-04-20 14:43
Personally I think the fudge factor is too high. 100 on Sunday and 85 on Monday AM should never produce a fluctuating pattern, the closest values in the table for fluctuating on Monday AM are 81 and 90. If the user makes a mistake by more than 1 bell difference they should expect to get an incorrect prediction.

**Comment by scizzorz** [comment] 2020-04-20 15:19
I'm also running into this issue. My buy price was 91, and Monday AM price is an 87 (96% of buy price), which is _quite far_ out of the 85..90% range of 78..82 bells, yet it's still offering up a ~60% probability of a large spike. I haven't looked into the fudge factor code at all, but I would expect it only needs to account for +/- 1 bell in either direction for rounding errors. I entered my value 5 bells completely out of possibility for decreasing / large spike; it should not be presenting me with those as valid predictions anymore.

**Comment by theRTC204** [comment] 2020-04-20 16:57
> If the user makes a mistake by more than 1 bell difference they should expect to get an incorrect prediction.

> I haven't looked into the fudge factor code at all, but I would expect it only needs to account for +/- 1 bell in either direction for rounding errors.

The fudge factor isn't there to account for user input error - it's there to account for compound floating point rounding differences between JavaScript on x86 and C++ on ARM.

In theory, we should be able to fudge the numbers by +/- 1, however in practice that has proven to be untrue - if you look through the closed issues, you'll see a significant number of reported pattern match failures which resulted in the fudge factor being set to 5.

We tried 1, then 2, then 3, and so on. 5 was what was required to successfully provide a prediction for all the exaamples we were given of failed matches.

**Comment by scizzorz** [comment] 2020-04-20 18:32
> The fudge factor isn't there to account for user input error - it's there to account for compound floating point rounding differences between JavaScript on x86 and C++ on ARM.

Damn - it can seriously compound up to *5* bells difference?! Is there any correlation to the compounding over time? eg: could the Mon AM price be +/- 1 bell, but the Sat PM price could be +/- 5 bells?

**Comment by theRTC204** [comment] 2020-04-20 20:54
> Damn - it can seriously compound up to _5_ bells difference?! Is there any correlation to the compounding over time? eg: could the Mon AM price be +/- 1 bell, but the Sat PM price could be +/- 5 bells?

Well, there's a few things to consider here... even though the game's algorithm has been extracted, it's still not possible to take someone's values and toss them into the game's math to reproduce the exact result that the game would produced. This is because the values are generated by a seed value that is passed into the algorithm, and that seed value is never exposed anywhere. Without that seed, we are left to only being able to estimate the numbers by doing the math backwards based on the values the Player does know.

At the end of the day, the last few words of my previous paragraph are key - "values the _Player_ does know". Because all of the data we have is user provided, it's impossible to guarantee that the data is correct. Any number of human factors could cause the data to be tainted.

What we do know is, the original implementation has no fudge factor, but instead for a given price range it rounded the lower bounds down, and the higher bounds up. We initially thought this would give enough of a buffer, but that proved to be false.

A week ago we were getting multiple reports a day of people unable to find a matching pattern with the numbers they were getting in the game. Initially we assumed most of those were user-error, and fell back on the math to show that their numbers were seemingly impossible.

But, the number of reports grew as the site traffic grew. It became clear that something wasn't quite right. We know that the math we have matches the game's math as best it can for running the algorithm backgrouds from a price back to the rate that was used to calculate it. We account for floating point rounding in the same way that the game does, and we account for the fact that anywhere between `N.00001` and `N.99999` will produce `N`.

What we can't do is calculate the exact values as they came out on the Switch - not without having access to a Tegra X1 to run the code on and see how it handles floating point math.

All that is to say, it's a far more complicated problem to solve than I think any of us have the time, equipment or interest to investigate beyond what we already have... especially when a small amount of fudge factor addresses the concern almost completely.

**Comment by scizzorz** [comment] 2020-04-20 21:43
Hmm. That's a much more interesting problem than I was expecting it to be! I can certainly understand some of the decisions that went into adding the fudge factor, but on the flip side, I feel like I can no longer trust this tool to give me accurate predictions or statistics because of it. Like I mentioned in my first comment on this thread:

> My buy price was 91, and Monday AM price is an 87 (96% of buy price), which is quite far out of the 85..90% range of 78..82 bells, yet it's still offering up a ~60% probability of a large spike.

([permalink](https://turnipprophet.io/?prices=91.87...........&pattern=0))

When the tooling reports a 60% probability of Large Spike and a 30% probability of Decreasing when there's actually a 0% probability of either of those, it really becomes hard to trust its predictions for anything.

That said, I completely respect the work going into the tool and I've loved following it mature from the first release :smile: I totally understand that this is entirely a free project running on volunteer time and you owe me nothing at all - just want to offer some authentic user feedback. I wish I had some free time to really crack into it and contribute an alternative implementation.

**Comment by astranberg** [comment] 2020-04-20 22:07
Can we please have a switch to turn off fudge factor?

**Comment by theRTC204** [comment] 2020-04-20 22:58
> ... I feel like I can no longer trust this tool to give me accurate predictions

That's certainly a troubling thing to hear... after all, why build this if people aren't going to use it? Certainly an area that needs more discussion.

**Comment by theRTC204** [comment] 2020-04-20 23:00
> Can we please have a switch to turn off fudge factor?
> 
> > N.00001 and N.99999 will produce N.
> 
> I believe it produces N+1 (roundup)

The fudge factor definitely does not produce N+1 roundup, it intentionally produces N+5. The rounding happens in `intceil()` which has nothing to do with fudge factor.

That being said, yes we can probably add a toggle for the fudge factor.

**Comment by mikebryant** [comment] 2020-04-20 23:03
I'm doing some prep for this in #206 - I'm thinking to run the predictor without the fudge factor, and if we get no results run it again.

Starting by moving it to a class so I don't need to pass a fudge_factor variable through all the functions

**Comment by mikebryant** [comment] 2020-04-21 15:50
@XcellMiguel This has been fixed by #219

Thanks everyone for your feedback here :)

**Closed by mikebryant** 2020-04-21 15:50 UTC
Labels: prediction

**Comment by XcellMiguel** [comment] 2020-04-21 16:45
@mikebryant Nice, it looks way better now with my values (no more 1e-7% prediction values too :D) and the graph shows the expected small spike instead of the large one (which was false).

Thanks !
